## GEOMETRY GENERATOR
# Global bounds
[reference]
l = 20

[global]
x_min = -1200  # Global x range
x_max = 1200
y_min = -600  # Global y range
y_max = 600
z_min = -300  # Global z range
z_max = 900

# Bottom center wall bounds
[bottom_center]
x_min_VII = -700  # x range for bottom plate - VII
x_max_VII = 0
y_min_VII = -250  # y range for bottom plate - VII
y_max_VII = 250

# Safety distances
[safety]
sd_x_neg = 150  # Minimum distance to no-slip - slip transition (after rotation)
sd_x_pos = 300  # Minimum distance to no-slip - slip transition (after rotation)
sd_y = 100  # Minimum distance to no-slip - slip transition (after rotation)
md = 5      # Minimum distance between building surfaces

# Number of buildings
[buildings]
b_min = 5   # Minimum number of buildings
b_max = 20  # Maximum number of buildings

# Rectangular buildings
[rectangular]
l_min = 10   # Min edge length of rectangular buildings
l_max = 80   # Max edge length of rectangular buildings
a_max = 2.5  # Max aspect ratio for normal buildings

# Extreme rectangular buildings
[extreme]
E = 0.15     # Probability for extreme building
e_max = 5.0  # Max aspect ratio for extreme buildings

# Circular buildings
[circular]
C = 0.05     # Probability for circular building
d_min = 10   # Min diameter
d_max = 80   # Max diameter
phi = 32     # Circumferential resolution

# Building height range
[height]
h_min = 5    # Minimum height for normal/extreme/circular buildings
h_max = 80   # Maximum height

# Towers
[towers]
T = 0.07       # Probability for tower
t_min = 50     # Min edge length of tower base
t_max = 100    # Max edge length
s_min = 80     # Min tower height
s_max = 200    # Max tower height
w_max = 1.5    # Max aspect ratio for towers

# Roads
[roads]
r = 10         # Road width
rh_min = 3     # Min number of horizontal roads
rh_max = 8     # Max number of horizontal roads
rv_min = 3     # Min number of vertical roads
rv_max = 8     # Max number of vertical roads

## GRID GENERATOR m-AIA
[grid_mAIA]
RF = 1.06666666666667
RL_min = 8
RL_max_unif = 8
RL_max = 13
REF_b = 16
REF_w = 300
x_incr = 10
y_incr = 6
z_incr = 6

## SIMULATION m-AIA
[sim_mAIA]
tau = 800000
Re = 9300
tau_re_start = 1000
Delta_tau_re = 50000
Delta_tau_s = 100000
Delta_tau_r = 100000
RESTART = false
tau_r = 300000
TIME-AVERAGING = true
tau_a_start = 300000
tau_a_stop = 800000
Delta_tau_a = 25
RESET = true
MONITOR = true
